components:
  schemas:
    User:
      type: object
      properties:
        first_name:
          type: string
          required: true
        last_name:
          type: string
          required: true
        email:
          type: string
          required: true
          unique: true
        telegram_handle:
          type: string
        phone_number:
          type: string
        type:
          type: string
          required: true
          enum: [cafe, customer]
          default: customer
        provider:
          type: string
          required: true
          enum: [email, google, facebook]
          default: email
        provider_meta:
          type: object
        deleted_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - first_name
        - last_name
        - email
        - type
        - provider
    UserResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/User"
        - type: object
          properties:
            _id:
              type: string
              pattern: "^[0-9a-fA-F]{24}$"
              description: Unique identifier for the booking (ObjectId format)
          except:
            - hash_password
    UpdateUserRequest:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          unique: true
        phone_number:
          type: string
        telegram_handle:
          type: string
        password:
          type: string
